implement-storage-handlers
dadosjusbr/agregador pull request #1
Opened 2021-08-06 05:35 UTC by Manuel-Antunes

Esse PR
* instala dependecias de storage e de variáveis de ambiente
* cria uma função que pega os backups de um orgão em um determinado ano
* executa a função baseada num placeholder definido no main

2021-08-06 18:18 UTC, danielfireman requested changes

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +	MongoDBName string `envconfig:"MONGODB_NAME"`
Este também é requerido

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +	MongoURI    string `envconfig:"MONGODB_URI"`
Este também é requerido

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +	DBUrl  string `envconfig:"MONGODB_URI"`
Este não é necessário, é igual a que está abaixo.

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +	DBName string `envconfig:"MONGODB_NAME"`
Este não é necessário. É igual a que está abaixo.

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +func newClient(c config) (*storage.Client, error) {
Se você precisa desse cara aqui, melhor fazer ele público em storage, não?

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +	agenciesMonthlyInfo, err := client.Db.GetMonthlyInfo([]storage.Agency{{ID: "mppb"}}, 2020)
Criar um método para buscar apenas os backups?

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +		fmt.Println("an error ocorred")
Colocar qual foi o erro.

2021-08-06 18:18 UTC, danielfireman commented on main.go
> +		fmt.Println("an error ocorred")
colocar qual foi o erro

2021-08-06 18:50 UTC, Manuel-Antunes commented on main.go
> +	MongoDBName string `envconfig:"MONGODB_NAME"`
Ok

2021-08-06 18:50 UTC, Manuel-Antunes commented on main.go
> +func newClient(c config) (*storage.Client, error) {
Ok

2021-08-10 17:11 UTC, danielfireman requested changes

2021-08-10 17:11 UTC, danielfireman commented on main.go
> +		if agencyMonthlyInfo.Summary.MemberActive.Wage.Total+agencyMonthlyInfo.Summary.MemberActive.Perks.Total+agencyMonthlyInfo.Summary.MemberActive.Others.Total > 0 {
Precisa mesmo dessa condição?

2021-08-10 17:11 UTC, danielfireman commented on main.go
> +	agenciesMonthlyInfo, err := client.Db.GetMonthlyInfo([]storage.Agency{{ID: "mppb"}}, 2020)
```suggestion
	agenciesMonthlyInfo, err := client.Db.GetMonthlyInfo([]storage.Agency{{ID: agency}}, year)

```

2021-08-10 17:11 UTC, danielfireman commented on main.go
> +		return nil, fmt.Errorf("error fetching data")
```suggestion
		return nil, fmt.Errorf("error fetching data: %v", err)

```

2021-08-10 17:11 UTC, danielfireman commented on main.go
> +	for _, agencyMonthlyInfo := range agenciesMonthlyInfo["mppb"] {
```suggestion
	for _, agencyMonthlyInfo := range agenciesMonthlyInfo[agency] {

```

2021-08-10 17:36 UTC, danielfireman approved these changes

2021-08-10 19:16 UTC, merged