Download files from list
dadosjusbr/agregador pull request #2
Opened 2021-08-10 21:17 UTC by Manuel-Antunes

Esse PR
* atualiza o pacote do storage
* cria uma função que baixa os arquivos da lista de pacotes

2021-08-10 21:24 UTC, danielfireman requested changes

2021-08-10 21:24 UTC, danielfireman commented on main.go
> +	packages, err := getBackupData(2020, "mppb")
Receber o ano e o órgão como parâmetros ou flags.

2021-08-10 21:24 UTC, danielfireman commented on main.go
> +	fmt.Println("arquivos baixados")
Listar os arquivos baixados?

2021-08-10 21:24 UTC, danielfireman commented on main.go
> +func downloadFilesFromPackageList(year int, list []storage.Backup) {
Nós não guardamos apenas o pacote de dados (que é o que você quer). Você deve focar apenas em arquivos com extensão zip. Ignorando o restante

2021-08-10 22:18 UTC, Manuel-Antunes commented on main.go
> +	packages, err := getBackupData(2020, "mppb")
Ok

2021-08-10 22:19 UTC, Manuel-Antunes commented on main.go
> +	fmt.Println("arquivos baixados")
Pse, acabei percebendo isso depois e mandei numa outra PR, mas vou mandar nessa

2021-08-10 22:39 UTC, Manuel-Antunes commented on main.go
> +	fmt.Println("arquivos baixados")
Tipo, eu posso na hora de fazer o merge do outro pr #3  já trazer essa parte, pois está lá

2021-08-12 04:09 UTC, Manuel-Antunes commented on main.go
> +func downloadFilesFromPackageList(year int, list []storage.Backup) {
Eu não entendi direito professor

2021-08-12 04:09 UTC, Manuel-Antunes commented on main.go
> +func downloadFilesFromPackageList(year int, list []storage.Backup) {
Então o que eu tenho q fazer ?

2021-08-12 04:11 UTC, Manuel-Antunes commented on main.go
> +func downloadFilesFromPackageList(year int, list []storage.Backup) {
Acho que entendi, no caso eu devo impedir de baixar o arquivo caso ele não seja zip, hmm

2021-08-12 12:50 UTC, danielfireman requested changes

2021-08-12 12:50 UTC, danielfireman commented on main.go
> +func downloadFilesFromPackageList(year int, list []storage.Backup) {
Exatamente.

2021-08-12 12:50 UTC, danielfireman commented on main.go
> +		}
```suggestion
		if filepath.Ext(el.URL) == "zip" {
			f := fmt.Sprintf("downloads/%d-%d.zip", year, index+1)
			download(f, el.URL)
		}

```

2021-08-12 20:05 UTC, closed without merging