extract-files
dadosjusbr/agregador pull request #3
Opened 2021-08-10 22:16 UTC by Manuel-Antunes

Esse PR
* pega o retorno dos caminhos dos arquivos na função de baixar arquivos
* cria uma função pra extrair os arquivos baseado no caminho dos arquivos baixados

2021-08-11 00:46 UTC, danielfireman requested changes

2021-08-11 00:46 UTC, danielfireman commented on main.go
> +		defer r.Close()
Esse difer só vai rolar depois que sair da função (ele não rola a cada iteração do for loop)

se quiser fazer isso você deve criar uma função e chamar aqui, ou criar uma função anônima.

2021-08-11 00:46 UTC, danielfireman commented on main.go
> +		err := download(filepath, el.URL)
Você não deve fazer o downlod se não for um arquivo zip.

2021-08-11 00:46 UTC, danielfireman commented on main.go
> +			fpath := filepath.Join(fmt.Sprintf("downloads/data/%d", i+1), f.Name)
Você não precisa concatenar i. Lembre-se que cada arquivo vai ser referente a um órgão, mês, ano específico. Vamos tornar tudo mais claro usando isso.

2021-08-11 00:46 UTC, danielfireman commented on main.go
> +			if !strings.HasPrefix(fpath, filepath.Clean(fmt.Sprintf("downloads/data/%d", i+1))+string(os.PathSeparator)) {
Tornar mais claro.

2021-08-11 00:46 UTC, danielfireman commented on main.go
> +			outFile, err := os.OpenFile(fpath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
Usar os.Create

2021-08-11 00:46 UTC, danielfireman commented on main.go
> +			filenames = append(filenames, fpath)
Não devemos extrair todos os arquivos. Só precisamos extrair os arquivos `data.csv`

ELes foram empacotados [aqui](https://github.com/dadosjusbr/coletores/blob/master/packager/main.go)

2021-08-12 04:37 UTC, Manuel-Antunes commented on main.go
> +			fpath := filepath.Join(fmt.Sprintf("downloads/data/%d", i+1), f.Name)
Então nesse caso, o senhor acha que seria melhor ao invés de pegar uma lista de packages, pegar todos os dados, inclusive id month e etc ?

2021-08-12 12:51 UTC, danielfireman commented on main.go
> +			fpath := filepath.Join(fmt.Sprintf("downloads/data/%d", i+1), f.Name)
Acho que o mês e o ano sim. O summary, não.

2021-08-12 20:36 UTC, closed without merging