Refactor agreggator
dadosjusbr/agregador pull request #7
Opened 2021-08-27 05:25 UTC by Manuel-Antunes

Esse PR

* cria uma flag para selecionar o tipo de agregação que será efetuada
* separa funções uteis para o agregador para reutilizações futuras
* separa a responsabilidade de agregar os dados de um órgão por ano dentro de uma função
* verifica a existência da flag de  órgão apenas dentro do contexto de agregação por órgão singular/ano
* cria uma função para agregar os dados de todos os órgãos por ano
* deleta os arquivos csv extraídos de cada agregação após serem lidos

2021-08-29 22:00 UTC, danielfireman requested changes

2021-08-29 22:00 UTC, danielfireman commented on main.go
> +	case "agency/year/all":
???

2021-08-31 02:29 UTC, Manuel-Antunes commented
Professor, é que o próximo PR já resolve a maioria dessas issues, aí tipo, tem que mesmo assim fazer as correções ? @danielfireman

2021-08-31 12:41 UTC, danielfireman commented on main.go
> +func agregateDataByAgencyYearFromAllAgencies(year int, outDir string) error {
???

2021-08-31 17:42 UTC, danielfireman approved these changes

2021-09-27 23:37 UTC, danielfireman approved these changes

2021-09-30 19:59 UTC, merged